name: extract
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install meltano
      - run: meltano install
      - run: meltano elt tap-wordpress target-jsonl
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/*
