name: extract
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ hashFiles('meltano.yml') }}-pip
      - run: python -m pip install meltano
      - uses: actions/cache@v2
        with:
          path: ./.meltano
          key: ${{ hashFiles('meltano.yml') }}-meltano
      - run: meltano install
      - run: rm output/*.jsonl
      - run: meltano elt tap-wordpress target-jsonl
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: output
      #     path: output/*.jsonl
      - name: push changes to remote
        continue-on-error: true
        run: |
          git config --global user.name "Luis Atala"
          git config --global user.email "luis@atala.co"
          git add output
          git commit -m "update output file"
          git push